---
title: "0104_data_merge"
author: "Christine Buje Hostrup Thier"
date: "2023-01-31"
output: html_document
fig_width: 10
fig_height: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(stringr)
library(readxl)
```

## Read data
```{r}
data <- read.csv("/Users/christinethier/Desktop/CBS Cand.Merc.(Mat.)/Speciale/XGBoost - R/database/0103_python_modify.csv",header = TRUE)
data_new <- read.csv("/Users/christinethier/Desktop/CBS Cand.Merc.(Mat.)/Speciale/XGBoost - R/database/0103_python_modify_new.csv",header = TRUE)
data_RK <- read_excel("/Users/christinethier/Desktop/CBS Cand.Merc.(Mat.)/Speciale/XGBoost - R/Excel-filer/2023131111049406520281DNRNURI.xlsx")
data_KS <- read_excel("/Users/christinethier/Desktop/CBS Cand.Merc.(Mat.)/Speciale/XGBoost - R/Excel-filer/kommuneskat data.xls")
```
```{r}
plot(Effektiv_rentesats, )
```


## Data modify
```{r}
RK_function <- function(x){
  x <- x %>% 
    slice(-c(1:2, 63:64)) %>% 
    select(c("...6","...7")) %>% 
    rename(c("year_month"="...6", "Effektiv_rentesats"="...7")) %>% 
    mutate(year = as.integer(str_extract(year_month, "^.{4}")),
           month =as.integer(str_extract(year_month,".{2}$"))) %>% 
    select(-c("year_month"))
    
}

KS_function <- function(x){
  x <- x %>% 
    slice(-c(1:3)) %>% 
    select(c(Kommune...3, Skatte, Kirke, Nedslag, År)) %>% 
    mutate(kommunenr = as.integer(Kommune...3)) %>% 
    rename("year"="År", "skattepct"="Skatte", "kirkepct"="Kirke") 
}
```

```{r}
data_RK <- RK_function(data_RK)
data_KS <- KS_function(data_KS)
```

## Data merge
```{r}
data <- data %>% 
  bind_rows(data_new)


data <- data %>% 
  filter(lat > 0 & long >0 & boligtype == "Alm Salg" & byggear >0 & !is.na(etagenr)) %>%
  mutate(alder = 2023-byggear,
         etagenr = as.numeric(etagenr)) %>% 
  left_join(data_RK, by=c("year","month")) %>% 
  left_join(data_KS, by=c("year","kommunenr")) %>% 
  select(c(pris, salgsdato, bolig, vaerelser, m2, alder, kommunenr, etagenr, lat, long, Effektiv_rentesats, skattepct, kirkepct)) 
  
```



## Save Data
```{r}
write.csv(data, "/Users/christinethier/Desktop/CBS Cand.Merc.(Mat.)/Speciale/XGBoost - R/database/0104_data_clean_new.csv", row.names=FALSE)
```

```{r}
data <-read.csv("/Users/christinethier/Desktop/CBS Cand.Merc.(Mat.)/Speciale/XGBoost - R/database/0104_data_clean_new.csv")
```


```{r}
residualer <- read.csv("/Users/christinethier/Desktop/CBS Cand.Merc.(Mat.)/Speciale/XGBoost - R/database/final_results/rf_df_res_fit.csv")
```

```{r fig1, fig.width=5,fig.height=5}
plot(residualer~fitted.værdier,residualer[sample(1:nrow(residualer),size=1000,replace=F),])
```

```{r fig2, fig.width=5,fig.height=5}
 plot(residualer~cut(fitted.værdier,quantile(fitted.værdier,0:10/10)),residualer,xlab='deciler')
```

```{r fig3, fig.width=5,fig.height=5}
library(sm)
sm.regression(residualer$fitted.værdier,abs(residualer$residualer),pch='.',col.points='grey',model='linear', xlab='fittede værdier', ylab = 'absolutte residualer')
```
```{r fig4, fig.width=5,fig.height=5}
tmp <- sm.regression(residualer$fitted.værdier,residualer$residualer,pch='.',col.points='grey',model='linear')
sm.regression(residualer$fitted.værdier,residualer$residualer,pch='.',col.points='grey',model='linear',  xlab='fittede værdier', ylab = 'residualer')
lines(tmp$eval.points,tmp$estimate)
mean(residualer$residualer)
```

```{r}
# Beregn de sande værdier, juster fittede værdier og beregn MSE
result <- residualer %>%
  rename("fittede"="fitted.værdier") %>% 
  mutate(
    fittede = as.numeric(fittede),
    residualer = as.numeric(residualer),
    true_values = fittede + residualer,
    mean_residuals = mean(residualer),
    fitted_values_adj = fittede + mean_residuals
  ) %>%
  summarize(
    MSE = mean((true_values - fitted_values_adj)^2)
  )
```


